
from pathlib import Path

import typer
import pandas as pd
import os

from config import (
    PROCESSED_DATA_DIR,
    RAW_DATA_DIR,
    MERGED_DATA_DIR,
    EXTERNAL_DATA_DIR,
    TRAIN_TEST_DIR,
)
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from process_cve import process_cve_batches, merge_batch_results
app = typer.Typer()

# function generated by ChatGPT-5 on November 19, 2025
def clean_ml(df):
    # Convert datetime columns
    for col in ['published_date', 'last_modified_date']:
        if col in df:
            df[col] = pd.to_datetime(df[col])
            df[col + '_age_days'] = (pd.Timestamp.now() - df[col]).dt.days


    # Target
    y = df['exploited'].astype(int)


    # Useful numeric cols
    numeric_cols = [
    'base_score','exploitability_score','impact_score',
    'published_date_age_days','last_modified_date_age_days'
    ]
    numeric_cols = [c for c in numeric_cols if c in df]


    # Useful categorical cols
    cat_cols = [
    'attack_vector','attack_complexity','privileges_required','user_interaction',
    'scope','confidentiality_impact','integrity_impact','availability_impact',
    'cwe_id','criteria','version','base_severity'
    ]
    cat_cols = [c for c in cat_cols if c in df]


    X = df[numeric_cols + cat_cols]


    # preprocessor
    numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ])


    categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore')),
    ])


    preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, cat_cols)
        ]
    )
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, stratify=y, random_state=42)
    return X_train, X_test, y_train,y_test, preprocessor

@app.command()
def main(
    input_path: Path = RAW_DATA_DIR / "CVE2024.csv",
    process_path: Path = PROCESSED_DATA_DIR,
    output_path: Path = MERGED_DATA_DIR,
):
    
    df = pd.read_csv(f"{MERGED_DATA_DIR}/Main1.csv")

    X_train, X_test, y_train, y_test, preprocessor = clean_ml(df)
    

    

if __name__ == "__main__":
    app()
