
from pydantic import BaseModel, Field, field_validator
from typing import List


# Base class generated by Gemini 3 Pro on November 22, 2025
EXPECTED_VECTOR_LENGTH = 91
class VectorInput(BaseModel):
    # Change: List[float] -> List[List[float]] to support batches
    features: List[List[float]] = Field(
        ..., 
        min_length=1, # Ensure at least one vector is sent
        description=f"Batch of feature vectors. Each inner vector must be exactly {EXPECTED_VECTOR_LENGTH} floats."
    )

    # Combined Validator: Checks shape (inner length) and content (NaNs)
    @field_validator('features')
    def validate_batch(cls, batch):
        for index, vector in enumerate(batch):
            # 1. Check Length of each vector
            if len(vector) != EXPECTED_VECTOR_LENGTH:
                raise ValueError(
                    f"Vector at index {index} has length {len(vector)}, "
                    f"expected {EXPECTED_VECTOR_LENGTH}."
                )
            
            # 2. Check for NaNs in each vector
            if any(x != x for x in vector): # Standard Python NaN check
                raise ValueError(f"Vector at index {index} contains NaN values.")
                
        return batch

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "features": [
                        # Vector 1
                        [0.1] * EXPECTED_VECTOR_LENGTH,
                        # Vector 2
                        [0.0] * EXPECTED_VECTOR_LENGTH
                    ]
                }
            ]
        }
    }
class PredictionOutput(BaseModel):
    predicted_class: int = Field(..., description="The class index (0 or 1)")
    probability: float = Field(..., description="Confidence probability score")


class BatchPredictionOutput(BaseModel):
    batch_results: List[PredictionOutput]